const eventsData = [
  {
    title: "Grand Opening Promo",
    description: "Celebrate our grand opening with freshly baked breads and exclusive in-store discounts.",
    date: "March 15, 2025",
    month: "March",
    day: "15",
    time: "8:00 AM – 6:00 PM",
    location: "Kabayans Bakeshop – Main Branch",
    image: "./imagesForGallery/ImagesForEvents/grand-opening.jpg",
  },
  {
    title: "Fresh Pandesal Morning",
    description: "Enjoy hot pandesal straight from the oven, perfect for your morning coffee.",
    date: "Every Saturday",
    month: "Every Month",
    day: "Saturday",
    time: "6:00 AM – 9:00 AM",
    location: "All Kabayans Bakeshop Branches",
    image: "./imagesForGallery/ImagesForEvents/pandesal-morning.jpg",
  },
  {
    title: "Holiday Bread Specials",
    description: "Limited-edition breads and pastries made specially for the holiday season.",
    date: "December 1 – December 24, 2025",
    month: "December",
    day: "1–24",
    time: "All Day",
    location: "Selected Branches",
    image: "./imagesForGallery/ImagesForEvents/holiday-special.jpg",
  },
  {
    title: "Buy 2 Get 1 Free Friday",
    description: "Bring your family and enjoy our Buy 2 Get 1 Free promo on selected items.",
    date: "Every Friday",
    month: "Every Month",
    day: "Friday",
    time: "2:00 PM – 7:00 PM",
    location: "Main Branch Only",
    image: "./imagesForGallery/ImagesForEvents/buy2get1.jpg",
  },
  {
    title: "Chocolate Croissant Week",
    description: "Celebrate the week with our delicious chocolate croissants at a special price.",
    date: "April 7 – April 13, 2025",
    month: "April",
    day: "7–13",
    time: "All Day",
    location: "All Kabayans Bakeshop Branches",
    image: "./imagesForGallery/ImagesForEvents/choco-croissant.jpg",
  },
  {
    title: "Customer Appreciation Day",
    description: "We appreciate our customers! Free mini pastries for every purchase over ₱500.",
    date: "May 20, 2025",
    month: "May",
    day: "20",
    time: "10:00 AM – 5:00 PM",
    location: "Main Branch",
    image: "./imagesForGallery/ImagesForEvents/customer-appreciation.jpg",
  },
];


export default  eventsData;