const sampleUsers = [
  {
    id:1,  
    email: "admin@company.com",
    fullname: "Angelo Garcia",
    password: "Admin@123",
    dateRegistered: "2024-01-05",
    role: "admin",
  },
  {
    id:2,
    email: "maria.santos@gmail.com",
    fullname: "Maria Santos",
    password: "MariaPass01",
    dateRegistered: "2024-02-12",
    role: "user",
  },
  {
    id:3,
    email: "paolo.reyes@yahoo.com",
    fullname: "Paolo Reyes",
    password: "Paolo2024",
    dateRegistered: "2024-03-01",
    role: "user",
  },
  {
    id:4,
    email: "angelica.lopez@gmail.com",
    fullname: "Angelica Lopez",
    password: "AngelicaPwd",
    dateRegistered: "2024-03-18",
    role: "user",
  },
  {
    id:5,
    email: "mark.villanueva@gmail.com",
    fullname: "Mark Villanueva",
    password: "Mark@456",
    dateRegistered: "2024-04-02",
    role: "staff",
  },
  {
    id:6,
    email: "joshua.mendoza@gmail.com",
    fullname: "Joshua Mendoza",
    password: "JoshMendoza",
    dateRegistered: "2024-04-20",
    role: "user",
  },
  {
    id:7,
    email: "karen.bautista@gmail.com",
    fullname: "Karen Bautista",
    password: "KarenPass",
    dateRegistered: "2024-05-05",
    role: "staff",
  },
  {
    id:8,
    email: "ronald.garcia@gmail.com",
    fullname: "Ronald Garcia",
    password: "RonGarcia1",
    dateRegistered: "2024-05-19",
    role: "user",
  },
  {
    id:9,
    email: "liza.torres@gmail.com",
    fullname: "Liza Torres",
    password: "Liza@2024",
    dateRegistered: "2024-06-01",
    role: "user",
  },
  {
    id:10,
    email: "supervisor@company.com",
    fullname: "Carlos Navarro",
    password: "Supervisor99",
    dateRegistered: "2024-06-15",
    role: "admin",
  },
];

export default sampleUsers;